backend:
  name: github
  repo: vinuch/my-blog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "contents/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "tags", name: "tags", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "excerpt", name: "excerpt", widget: "string"}
      - {label: "created", name: "created", widget: "date"}
      - {label: "image", name: "image", widget: "image",  default: "/uploads/chocolate-dogecoin.jpg", media_library: config: multiple: true}
      - {label: "image_caption", name: "image_caption", widget: "string"}
      - {label: "author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "authors"
    label: "Authors"
    folder: "contents/author"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "id", name: "id", widget: "string"}
      - {label: "name", name: "name", widget: "string"}
      - {label: "bio", name: "", widget: "string"}
      - {label: "facebook", name: "", widget: "string"}
      - {label: "twitter", name: "", widget: "string"}
      - {label: "linkedin", name: "", widget: "string"}
      - {label: "image", name: "", widget: "string"}